# Ktor Config
server {
  port = 8888
  port = ${?KL_SERVER_PORT}
  module = "com.kitledger.ApplicationKt.module"
}

db {
  url = "jdbc:postgres://localhost:5432/kitledger"
  url = ${?KL_POSTGRES_URL}
  maxConnections = 10
  maxConnections = ${?KL_POSTGRES_MAX_CONNECTIONS}
}

auth {
  secret = ${KL_AUTH_SECRET}
  pastSecrets = []
  pastSecrets = ${?KL_AUTH_PAST_SECRETS}
}

session {
  ttl = 3600
  ttl = ${?KL_SESSION_TTL}
}

cors {
  origin = []
  origin = ${?KL_CORS_ALLOWED_ORIGINS}
  additionalHeaders = []
  additionalHeaders = ${?KL_CORS_ALLOWED_HEADERS}
  maxAge = 86400
  maxAge = ${?KL_CORS_MAX_AGE}
}
